"""Add project_updates, security_alerts, two_factor_enabled to User

Revision ID: 070b312ada57
Revises: 
Create Date: 2025-04-17 13:39:25.423717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070b312ada57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_updates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('security_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('security_alerts')
        batch_op.drop_column('project_updates')

    # ### end Alembic commands ###
